# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-7"

  config.vm.provision :shell, :path => "redis-scripts/install.sh"
  config.vm.synced_folder "./redis-scripts", "/home/vagrant/redis-scripts"


  config.vm.network "forwarded_port", guest: 4000, host: 4000
  config.vm.network "forwarded_port", guest: 4001, host: 4001
  config.vm.network "forwarded_port", guest: 4002, host: 4002

  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 5001, host: 5001
  config.vm.network "forwarded_port", guest: 5002, host: 5002

  config.vm.network "forwarded_port", guest: 6000, host: 6000
  config.vm.network "forwarded_port", guest: 6001, host: 6001

  config.vm.network "forwarded_port", guest: 6010, host: 6020
  config.vm.network "forwarded_port", guest: 6011, host: 6021

  config.vm.network "forwarded_port", guest: 6020, host: 6020
  config.vm.network "forwarded_port", guest: 6021, host: 6021

  config.vm.network "forwarded_port", guest: 7000, host: 7000
  config.vm.network "forwarded_port", guest: 7001, host: 7001

  config.vm.network "forwarded_port", guest: 7010, host: 7010
  config.vm.network "forwarded_port", guest: 7011, host: 7011

  config.vm.network "forwarded_port", guest: 7020, host: 7020
  config.vm.network "forwarded_port", guest: 7021, host: 7021
end
